name: "📄 Blank Issue"
description: "Create a new issue when no other template applies."
title: "[Custom Issue]: "  # Placeholder for users to enter their own title
labels: [ "needs-triage", "custom-issue" ]
assignees:
  - your-github-username  # Optional, auto-assigns issues to a user

body:
  - type: markdown
    attributes:
      value: "## 🚀 Describe Your Issue\n*Please provide a clear and concise description of your issue.*"

  - type: textarea
    id: issue_description
    attributes:
      label: "📝 Issue Description"
      description: "Provide details about the issue, including expected vs. actual behavior."
      placeholder: "I encountered an issue while..."
    validations:
      required: true

  - type: input
    id: steps_to_reproduce
    attributes:
      label: "⚡ Steps to Reproduce"
      description: "List the steps to reproduce this issue."
      placeholder: "1. Go to...\n2. Click on...\n3. See the error"

  - type: dropdown
    id: severity
    attributes:
      label: "📌 Severity Level"
      description: "How severe is this issue?"
      options:
        - "❗ Critical - Blocks the app"
        - "⚠️ High - Major problem"
        - "🟡 Medium - Minor issue"
        - "🟢 Low - Cosmetic issue"
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "💡 Additional Context (Logs, Screenshots, Videos)"
      description: "Upload any relevant logs, screenshots, or video links."
      placeholder: "Attach images/videos or add links here."

  - type: checkboxes
    id: confirmation
    attributes:
      label: "✅ Confirmation"
      description: "Before submitting, please confirm the following:"
      options:
        - label: "I have searched for similar issues before submitting."
          required: true
        - label: "I have provided all necessary details and screenshots if applicable."
          required: true