name: "Blank Issue"
description: "Use this template to create a custom issue with a proper title, description, and attachments."
title: "[Custom Issue] <Enter a meaningful title here>"
labels: ["custom-issue", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: "## 📝 Describe the Issue\nProvide a clear and concise description of your issue."

  - type: textarea
    id: issue_description
    attributes:
      label: "📌 Issue Description"
      description: "Explain the issue in detail. If applicable, include code snippets or logs."
      placeholder: "Write a detailed issue description here..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 Steps to Reproduce (Optional)"
      description: "List the steps to reproduce the issue."
      placeholder: |
        1. Go to...
        2. Click on...
        3. See the error...
  
  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "The expected outcome should be..."
  
  - type: textarea
    id: actual_behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "Describe what actually happened."
      placeholder: "The actual outcome was..."
  
  - type: dropdown
    id: priority
    attributes:
      label: "📊 Priority Level"
      description: "How urgent is this issue?"
      options:
        - "High"
        - "Medium"
        - "Low"
  
  - type: textarea
    id: additional_context
    attributes:
      label: "📎 Additional Context (Screenshots/Videos)"
      description: "Attach any relevant images or videos here."
      placeholder: "Drag and drop images/videos or provide links."
  
  - type: checkboxes
    id: checklist
    attributes:
      label: "✔️ Checklist"
      description: "Before submitting, please confirm:"
      options:
        - label: "I have searched for duplicate issues."
          required: true
        - label: "I have read the contributing guidelines."
          required: true